### ISSUE TITLE
Fails to run in development mode

### ISSUE THREAD

**Issue by johnknoop** [metonym/svelte-rollup-template#46]
Hi

I simply followed the guide in the readme, but when I open localhost:3000, I get a 500 response with this content:

> 
> 500 Internal Server Error
> 
> C:\svelte-test\build
> 
> -4068
> EISDIR
> read
> 
> (rollup-plugin-serve)

Yarn version: 1.22.0
Node version: v12.18.0

**Comment by johnknoop** [comment]
Solution: use v1.0.1 of rollup-plugn-serve

**Comment by metonym** [comment]
FWIW I think it's related to rollup-plugin-livereload ([issue](https://github.com/thgh/rollup-plugin-livereload/issues/51))
