### ISSUE TITLE
Writing CSS to file will no longer be an option in rollup-plugin-svelte 7.0

### ISSUE THREAD

**Issue by diiq** [metonym/svelte-rollup-template#48]
Thanks for writing this template, it's been a big help.

Like I fool, I attempted to borrow only the parts I needed, and discovered its CSS handling is incompatible with rollup-plugin-svelte ^7.0.0 due to https://github.com/sveltejs/rollup-plugin-svelte/pull/147

**This is a warning, not a bug** -- the template still works as written, but will break when you upgrade the dependencies.

**Comment by metonym** [comment]
@diiq Thank you for raising this issue.

PR #49 includes:

- upgrade `rollup-plugin-svelte` to version 7.x
- add `rollup-plugin-css-only` to handle emitted CSS

[rollup.config.js](https://github.com/metonym/svelte-rollup-template/pull/49/files#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45c) has been adjusted accordingly.
